#!/usr/bin/env python3

import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind(("10.8.0.1", 7777))
s.listen(1)

print("Echo server listening on port 9999...")
conn, addr = s.accept()

print(f"Connection from {addr}")

while True:
    data = conn.recv(3)
    if not data:
        break
    print(f"Received: {data}")
    conn.sendall(data)
conn.close()
